/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASE 0x40021400
#define RCC_CR (*((volatile uint32_t *)(RCC_BASE)))
#define RCC_CFGR (*((volatile uint32_t *)(RCC_BASE + 0x04 )))
#define RCC_APB2ENR (*((volatile uint32_t *)(RCC_BASE + 0x18)))

#define GPIOA_BASE  0x40010800
#define GPIOA_CRL 	*((volatile uint32_t *)(GPIOA_BASE +  0x00))
#define GPIOA_CRH 	*((volatile uint32_t *)(GPIOA_BASE +  0x04))
#define GPIOA_ODR 	*((volatile uint32_t *)(GPIOA_BASE +  0x0C))
#define GPIOA_IDR 	*((volatile uint32_t *)(GPIOA_BASE +  0x08))

#define GPIOB_BASE  0x40010C00
#define GPIOB_CRL 	*((volatile uint32_t *)(GPIOB_BASE))
#define GPIOB_CRH 	*((volatile uint32_t *)(GPIOB_BASE + 0x04 ))
#define GPIOB_ODR   *((volatile uint32_t *)(GPIOB_BASE + 0x0C ))


void Clock_init()
{



}
void GPIOB_init()
{
	RCC_APB2ENR |= (0b11 << 2); // enable port A & B
	// 00: General purpose output push-pull Bits : 7 6
	GPIOB_CRL |= ( 0b01 << 4) ;
	GPIOB_CRL &= ~( 0b11 << 6) ;
	// 00: General purpose output push-pull Bits : 23 22
	GPIOB_CRL |= ( 0b01 << 20) ;
	GPIOB_CRH &= ~( 0b11 << 22);
}
void GPIOA_init()
{
	GPIOA_CRL = 0;
	GPIOA_CRH = 0;
	/*
	 In input mode (MODE[1:0]=00):
	00: Analog mode
	01: Floating input (reset state)
	10: Input with pull-up / pull-down
	11: Reserved
	In output mode (MODE[1:0] > 00):
	00: General purpose output push-pull
	  */
	GPIOA_CRL |= (1 << 6);
	GPIOA_CRH |= (1 << 22);


}
int main(void)
{
	volatile int i;
	Clock_init();
	GPIOB_init();
	GPIOA_init();
	/* Loop forever*/
	while(1)
	{
		if( ( (GPIOA_IDR & ( 1 << 1)) >> 1) == 0)
		{
			GPIOB_ODR ^= ( 1 << 1);
			while(( ((GPIOA_IDR & ( 1 << 1)) >> 1)== 0));
		}
		if(( (GPIOA_IDR & ( 1 << 13)) >> 13) == 0 )
		{
			GPIOB_ODR ^= ( 1 << 13);
		}
		for( i = 0 ; i < 500; i++);
	}
}



